# The Site Settings
# v2.0
# https://github.com/cotes2020/jekyll-theme-chirpy
# © 2017-2019 Cotes Chung
# MIT licensed


# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
#--------------------------

title: Mobile46.Net                          # the main title

tagline: Tersine mühendislik ve yazılım ile ilgili bilgiler.  # it will display as the sub-title

description: >-                        # used by seo meta and the atom feed
  Tersine mühendislik ve yazılım ile ilgili bilgiler.

# Replace with the website url, e.g. 'https://username.github.io'
url: 'https://mobile46.net'

author: Mobile46                  # change to your full name

avatar: /assets/img/logo.png   # support internet resources

github:
  username: Mobile46             # change to your github username

twitter:
  username: MoFoSiX            # change to your twitter username

social:
  name: Mobile46                  # it will shows as the copyright owner in Footer
  email: byzlo685@gmail.com             # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://github.com/Mobile46       # change to your github homepage
    - https://twitter.com/MoFoSiX      # change to your twitter homepage
    - https://facebook.com/MoFoSiX
    - https://linkedin.com/in/MoFoSiX

google_site_verification: QDI1yAiFQteoaiy6NeAkPnZcJ6iOTridUJxwWHNWfTY # change to your verification string

#--------------------------


# Only if your site type is GitHub Project sites and doesn't have a custom domain,
# change below value to '/projectname'.
baseurl: ''

# Change to your timezone › http://www.timezoneconverter.com/cgi-bin/findzone/findzone
timezone: Europe/Istanbul

google_analytics:
  id: 'UA-97319433-1'          # Fill with your Google Analytics ID
  pv:
    # The Google Analytics pageviews switch.
    # DO NOT enable it unless you know how to deploy the Google Analytics superProxy.
    enabled: false
    # the next options only valid when `google_analytics.pv` is enabled.
    proxy_url: ''
    proxy_endpoint: ''
    cache: false  # pv data local cache, good for the users from GFW area.

disqus:
  comments: true  # boolean type, the global switch for posts comments.
  shortname: 'mobile46'    # Fill with your Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname


# Prefer color scheme setting, available values:
#
#     dual   - Follow the system prefer color by default, and a toggle will display
#              in the left bottom of Sidebar, which used for switch the theme between dark and light.
#
#     light  - Use the light color scheme
#
#     dark   - Use the dark color scheme
#
theme_mode: dark

# boolean type, global switch for ToC in posts.
toc: true

paginate: 10

markdown: kramdown

highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# DO NOT change this unless you're a Pro user on Jekyll and Web development,
# or you think you're smart enough to change other relevant URLs within this template.
permalink: /posts/:title/

defaults:
  -
    scope:
      path: ""          # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true    # Enable comments in posts.
      toc: true         # Display TOC column in posts.
      location: Post
      breadcrumb:
        -
          label: Blog
          url: /
  -
    scope:
      path: _drafts
    values:
      comments: false
  -
    scope:
      path: tags
    values:
      tab_active: Etiketler
      location: Tag
      breadcrumb:
        -
          label: Ana sayfa
          url: /
        -
          label: Etiketler
          url: /tabs/tags/
  -
    scope:
      path: categories
    values:
      tab_active: Kategoriler
      location: Category
      breadcrumb:
        -
          label: Ana sayfa
          url: /
        -
          label: Kategoriler
          url: /tabs/categories/
  -
    scope:
      path: tabs
    values:
      layout: page
      dynamic_title: true    # Hide title in mobile screens.
      breadcrumb:
        -
          label: Ana sayfa
          url: /


sass:
  sass_dir: /assets/css
  style: compressed

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: [html, head, body, dt, dd, rt, rp,
            optgroup, option, colgroup, caption,
            thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []

exclude:
  - vendor        # Avoid Jekyll mistakenly read the vendor directory on Travis-CI's VM .
  - Gemfile.lock
  - Gemfile
  - tools
  - docs
  - README.md
  - LICENSE

sitemap_exclude:  # Sitemap will exclude the following items.
  fuzzy:
    - /assets/
  accurate:
    - /norobots/
    - /tabs/
    - /categories/
    - /tags/
    - /posts/
    - 404.html
    - feed.xml
    - sitemap.xml
    - robots.txt
    - redirects.json
